
name: release-prod

on:
  push:
      branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ closed ]


jobs:
  release-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Test project
        run: npm run test

      - name: Release Check
        run: python ./utils/release_check.py

      - name: Pushes to prod repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './dist'
          destination-github-username: 'fsImageries'
          destination-repository-name: 'rev_space_timeline_prod'
          target-branch: gh-pages