# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Basic Pipeline

on:
  push:
    branches: ["dev"] #[ "main", "dev" ]
  pull_request:
    branches: ["dev"] #[ "main", "dev" ]

env:
  BASE_DIR: basedir

jobs:
  basic_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint project
        run: npm run lint

      - name: Prettify project
        run: npm run pretty

      - name: Build project
        run: npm run build
        
      - name: Test project
        run: npm run test

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Applied formatting changes
          branch: ${{ github.head_ref }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/dev' && (github.event_name == 'push' || github.event.pull_request.merged == true)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  
  



